// Build-time CSS processor.
//
// Reads the authored stylesheet at src/theme/table.css, inlines every
// `url(icons/NAME.svg)` reference as a `data:` URI so the shipped stylesheet is
// a single portable file (no sibling asset folder to serve), and emits:
//
//   dist/index.css                     the publishable stylesheet
//   src/theme/styles.generated.ts      GRID_STYLES string (for injectGridStyles)
//   src/theme/cssVars.generated.ts     PteVarName union + PTE_VAR_NAMES array
//
// The generated .ts files are the single source of truth consumed by the theme
// module, so the inlined stylesheet and the injected-string variant never drift.
// Run via `npm run generate` (invoked by the pre* hooks) and `npm run build`.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const cssPath = join(root, "src", "theme", "table.css");
const iconsDir = join(root, "src", "theme", "icons");
const distDir = join(root, "dist");
const themeDir = join(root, "src", "theme");

/** Encode an inline SVG string as a compact `data:image/svg+xml,...` URI. Mirrors
 * svgToDataUrl() in src/theme/icons.ts so runtime overrides and build-time inlining
 * produce byte-identical output. */
function svgToDataUrl(svg) {
  const encoded = svg
    .replace(/\s+/g, " ")
    .replace(/"/g, "'")
    .replace(/%/g, "%25")
    .replace(/#/g, "%23")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E")
    .replace(/{/g, "%7B")
    .replace(/}/g, "%7D")
    .trim();
  return `data:image/svg+xml,${encoded}`;
}

function inlineIcons(css) {
  const missing = [];
  const inlined = css.replace(/url\(\s*icons\/([^)]+?\.svg)\s*\)/g, (_m, file) => {
    const iconPath = join(iconsDir, file);
    let svg;
    try {
      svg = readFileSync(iconPath, "utf8");
    } catch {
      missing.push(file);
      return `url(icons/${file})`;
    }
    return `url("${svgToDataUrl(svg)}")`;
  });
  if (missing.length) {
    throw new Error(`build-css: missing icon files: ${missing.join(", ")}`);
  }
  // Guard against any icon ref the regex above did not catch.
  const leftover = inlined.match(/url\(\s*icons\//);
  if (leftover) throw new Error("build-css: un-inlined icons/ reference remains");
  return inlined;
}

/** Collect every distinct `--pte-*` custom property name defined or referenced. */
function collectVarNames(css) {
  const names = new Set();
  for (const m of css.matchAll(/--pte-[a-zA-Z0-9-]+/g)) names.add(m[0]);
  return [...names].sort();
}

function tsStringLiteral(value) {
  // JSON.stringify yields a valid double-quoted TS string literal.
  return JSON.stringify(value);
}

function main() {
  const rawCss = readFileSync(cssPath, "utf8");
  const inlinedCss = inlineIcons(rawCss);
  const varNames = collectVarNames(rawCss);

  mkdirSync(distDir, { recursive: true });
  writeFileSync(join(distDir, "index.css"), inlinedCss);

  const banner = "// AUTO-GENERATED by scripts/build-css.mjs. Do not edit by hand.\n";

  writeFileSync(
    join(themeDir, "styles.generated.ts"),
    banner + `export const GRID_STYLES: string = ${tsStringLiteral(inlinedCss)};\n`,
  );

  const union = varNames.map((n) => `  | ${tsStringLiteral(n)}`).join("\n");
  writeFileSync(
    join(themeDir, "cssVars.generated.ts"),
    banner +
      `/** Every CSS custom property the grid stylesheet reads. */\n` +
      `export type PteVarName =\n${union};\n\n` +
      `export const PTE_VAR_NAMES: readonly PteVarName[] = [\n` +
      varNames.map((n) => `  ${tsStringLiteral(n)},`).join("\n") +
      `\n];\n`,
  );

  // Sanity: every icon file should have been referenced (helps catch dead icons).
  const iconFiles = readdirSync(iconsDir).filter((f) => f.endsWith(".svg"));
  const unreferenced = iconFiles.filter((f) => !rawCss.includes(`icons/${f}`));
  if (unreferenced.length) {
    console.warn(`build-css: warning — unreferenced icon files: ${unreferenced.join(", ")}`);
  }

  console.log(
    `build-css: dist/index.css (${inlinedCss.length} bytes), ${varNames.length} css vars, ${iconFiles.length} icons inlined`,
  );
}

main();
