#!/usr/bin/env node
// Changelog helpers. The root CHANGELOG.md is the single source of truth for release notes;
// this script carries it to the two places readers actually look, so nothing is written twice.
//
//   node scripts/changelog.mjs sync-docs
//       Writes apps/docs/docs/changelog.md (gitignored) from CHANGELOG.md with the front matter
//       Docusaurus needs and a stable `{#vX-Y-Z}` anchor on every version heading. Runs as the
//       docs workspace's `prestart` / `prebuild` hook, so `npm run docs:dev` and `docs:build`
//       (and therefore CI and the Vercel deploy) always render the current file.
//
//   node scripts/changelog.mjs section <version>
//       Prints the body of one version's entry on stdout. release.yml turns it into the GitHub
//       Release notes for the tag. Exits 1 when the version has no entry, so a forgotten
//       changelog fails that job loudly instead of shipping an empty release.
//
// Both commands key off the heading shape `## X.Y.Z — YYYY-MM-DD` (em dash). The date is
// optional for parsing but the pre-publish checklist asks for it; it becomes the docs page's
// "last updated" stamp, which keeps Docusaurus from asking git about an untracked file.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const changelogPath = resolve(repoRoot, "CHANGELOG.md");
const docsPagePath = resolve(repoRoot, "apps/docs/docs/changelog.md");
const editUrl = "https://github.com/agility-workbench/agility-workbench/edit/main/CHANGELOG.md";

const VERSION_HEADING =
  /^## (?<version>\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)(?:\s+—\s+(?<date>\d{4}-\d{2}-\d{2}))?\s*$/;

/** `1.4.0` -> `v1-4-0`; `1.5.0-beta.1` -> `v1-5-0-beta-1`. Shared by the docs anchors and release.yml. */
function anchorFor(version) {
  return `v${version.replace(/[^0-9A-Za-z]+/g, "-")}`;
}

function rel(path) {
  return relative(repoRoot, path);
}

function fail(message) {
  console.error(`changelog: ${message}`);
  process.exit(1);
}

function readChangelog() {
  if (!existsSync(changelogPath)) fail(`${rel(changelogPath)} does not exist.`);
  const lines = readFileSync(changelogPath, "utf8").split("\n");
  const entries = [];
  lines.forEach((line, index) => {
    const match = VERSION_HEADING.exec(line);
    if (match) entries.push({ version: match.groups.version, date: match.groups.date ?? null, line: index });
  });
  if (entries.length === 0) fail(`${rel(changelogPath)} has no "## X.Y.Z — YYYY-MM-DD" headings.`);
  return { lines, entries };
}

/** The lines between one version heading and the next, without surrounding blank lines. */
function sectionBody({ lines, entries }, version) {
  const index = entries.findIndex((entry) => entry.version === version);
  if (index === -1) return null;
  const start = entries[index].line + 1;
  const end = index + 1 < entries.length ? entries[index + 1].line : lines.length;
  const body = lines.slice(start, end);
  while (body.length && body[0].trim() === "") body.shift();
  while (body.length && body.at(-1).trim() === "") body.pop();
  return body.join("\n");
}

function syncDocs() {
  const changelog = readChangelog();
  const latest = changelog.entries[0];
  const body = changelog.lines
    .map((line) => {
      const match = VERSION_HEADING.exec(line);
      return match ? `${line.trimEnd()} {#${anchorFor(match.groups.version)}}` : line;
    })
    .join("\n");
  const frontMatter = [
    "---",
    "# GENERATED by scripts/changelog.mjs from the root CHANGELOG.md. Edit that file, not this one.",
    "title: Changelog",
    "description: What changed in each release of the grid and its React and Angular bindings.",
    `custom_edit_url: ${editUrl}`,
    ...(latest.date ? ["last_update:", `  date: ${latest.date}`] : []),
    "---",
    "",
  ].join("\n");
  const output = frontMatter + body;
  // Leave an unchanged file alone so `docusaurus start` sees no spurious change.
  if (existsSync(docsPagePath) && readFileSync(docsPagePath, "utf8") === output) return;
  mkdirSync(dirname(docsPagePath), { recursive: true });
  writeFileSync(docsPagePath, output);
  console.log(
    `changelog: wrote ${rel(docsPagePath)} (${changelog.entries.length} releases, latest ${latest.version})`,
  );
}

function printSection(versionArg) {
  if (!versionArg) fail("usage: node scripts/changelog.mjs section <version>");
  const version = versionArg.replace(/^v/, "");
  const body = sectionBody(readChangelog(), version);
  if (body === null) {
    fail(`${rel(changelogPath)} has no "## ${version} — YYYY-MM-DD" entry. Add one, then re-run the release.`);
  }
  process.stdout.write(`${body}\n`);
}

const [command, argument] = process.argv.slice(2);
switch (command) {
  case "sync-docs":
    syncDocs();
    break;
  case "section":
    printSection(argument);
    break;
  default:
    fail("usage: node scripts/changelog.mjs <sync-docs | section <version>>");
}
